version: '3.8'

services:
  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: takapedia_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - takapedia_network
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=takapedia
      - DB_USERNAME=takapedia
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  # Nginx Web Server  
  nginx:
    image: nginx:alpine
    container_name: takapedia_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - takapedia_network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: takapedia_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: takapedia
      MYSQL_USER: takapedia
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - takapedia_network

  # Redis Cache & Sessions
  redis:
    image: redis:7-alpine
    container_name: takapedia_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - takapedia_network

  # Queue Workers
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: takapedia_queue
    restart: unless-stopped
    command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --daemon
    volumes:
      - .:/var/www/html
    networks:
      - takapedia_network
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis

  # Scheduler (Cron Jobs)
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: takapedia_scheduler  
    restart: unless-stopped
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
    networks:
      - takapedia_network
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  takapedia_network:
    driver: bridge